mtbs:
  description: Raw datasets from MTBS
  metadata:
    url: https://www.mtbs.gov/
  data:
    burned_area_extent_shapefile:
      actions: [download, unzip]
      urlpath:
        - https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/MTBS_Fire/data/composite_data/burned_area_extent_shapefile/mtbs_perimeter_data.zip
    fod_pt_shapefile:
      actions: [wget, unzip]
      urlpath:
        - https://edcintl.cr.usgs.gov/downloads/sciweb1/shared/MTBS_Fire/data/composite_data/fod_pt_shapefile/mtbs_fod_pts_data.zip

mlrc:
  description: Raw datasets from MRLC
  metadata:
    url: https://www.mrlc.gov/data
  data:
    NLCD_Land_Cover_Change_Index_L48_20190424:
      actions: [download, unzip]
      urlpath:
        - https://s3-us-west-2.amazonaws.com/mrlc/NLCD_Land_Cover_Change_Index_L48_20190424.zip
    NLCD_Land_Cover_L48_20190424_full_zip:
      actions: [wget, unzip]
      urlpath:
        - https://s3-us-west-2.amazonaws.com/mrlc/NLCD_Land_Cover_L48_20190424_full_zip.zip
    NLCD_Land_Cover_AK_20200213:
      actions: [download, unzip]
      urlpath:
        - https://s3-us-west-2.amazonaws.com/mrlc/NLCD_2001_Land_Cover_AK_20200213.zip
        - https://s3-us-west-2.amazonaws.com/mrlc/NLCD_2011_Land_Cover_AK_20200213.zip
        - https://s3-us-west-2.amazonaws.com/mrlc/NLCD_2016_Land_Cover_AK_20200213.zip
    nlcd_treecanopy_2019_08_31:
      actions: [download, unzip]
      urlpath:
        - https://s3-us-west-2.amazonaws.com/mrlc/nlcd_2011_treecanopy_2019_08_31.zip
        - https://s3-us-west-2.amazonaws.com/mrlc/nlcd_2016_treecanopy_2019_08_31.zip

usfs:
  desription: Raw raster datasets from the US Forest Service raster gateway
  metadata:
    url: https://data.fs.usda.gov/geodata/rastergateway/
  data:
    conus_forestgroup:
      actions: [download, unzip]
      urlpath:
        - https://data.fs.usda.gov/geodata/rastergateway/forest_type/conus_forestgroup.zip
    conus_foresttype:
      actions: [download, unzip]
      urlpath:
        - https://data.fs.usda.gov/geodata/rastergateway/forest_type/conus_forest-type.zip
    ak_forestgroup:
      actions: [download, unzip]
      urlpath:
        - https://data.fs.usda.gov/geodata/rastergateway/forest_type/ak_forestgroup.zip
    ak_foresttype:
      actions: [download, unzip]
      urlpath:
        - https://data.fs.usda.gov/geodata/rastergateway/forest_type/ak_forest-type.zip

fia:
  description: Raw datasets from Forest Inventory Analysis
  metadata:
    url: https://apps.fs.usda.gov/fia/datamart/datamart.html
  data:
    entire:
      actions: [download, unzip]
      urlpath:
        - https://apps.fs.usda.gov/fia/datamart/CSV/ENTIRE.zip

gcp:
  description: Raw datasets from the Global Carbon Budget.
  metadata:
    url: https://www.icos-cp.eu/global-carbon-budget-2019
  data:
    global_budget_2019:
      actions: [manual]
      urlpath:
        - https://doi.org/10.18160/GCP-2019
    national_emissions_2019:
      actions: [manual]
      urlpath:
        - https://doi.org/10.18160/GCP-2019

iiasa:
  description: Raw datasets from the Global Carbon Budget.
  metadata:
    url:
  data:
    SSP_IAM_V2_201811:
      actions: [manual]
      urlpath:
        - https://tntcat.iiasa.ac.at/SspDb/download/iam_v2/SSP_IAM_V2_201811.csv.zip
    SSP_CMIP6_201811:
      actions: [manual]
      urlpath:
        - https://tntcat.iiasa.ac.at/SspDb/download/cmip6/SSP_CMIP6_201811.csv.zip
        - https://tntcat.iiasa.ac.at/SspDb/download/cmip6/cmip6_iam_model_region_mapping.xlsx
    SSP_BASIC_ELEMENTS:
      actions: [manual]
      urlpath:
        - https://tntcat.iiasa.ac.at/SspDb/download/basic_elements/SspDb_compare_regions_2013-06-12.csv.zip
        - https://tntcat.iiasa.ac.at/SspDb/download/basic_elements/SspDb_country_data_2013-06-12.csv.zip
    RCP_CMIP5:
      actions: [manual]
      urlpath:
        - https://tntcat.iiasa.ac.at/RcpDb/download/CMIP5RECOMMENDATIONS/PICNTRL_MIDYR_CONC.zip
        - https://tntcat.iiasa.ac.at/RcpDb/download/CMIP5RECOMMENDATIONS/PRE2005_MIDYR_CONC.zip
        - https://tntcat.iiasa.ac.at/RcpDb/download/CMIP5RECOMMENDATIONS/RCP3PD_MIDYR_CONC.zip
        - https://tntcat.iiasa.ac.at/RcpDb/download/CMIP5RECOMMENDATIONS/RCP45_MIDYR_CONC.zip
        - https://tntcat.iiasa.ac.at/RcpDb/download/CMIP5RECOMMENDATIONS/RCP6_MIDYR_CONC.zip
        - https://tntcat.iiasa.ac.at/RcpDb/download/CMIP5RECOMMENDATIONS/RCP85_MIDYR_CONC.zip
