name: carbonplan-data
channels:
  - conda-forge
  - nodefaults
dependencies:
  - dask
  - fastparquet
  - gcsfs
  - gdal
  - google-cloud-storage
  - intake
  - intake-geopandas
  - intake-parquet
  - intake-xarray
  - libgdal
  - netcdf4
  - pandas
  - pip
  - pooch
  - pydap
  - pytest
  - pytest-cov
  - rasterio
  - urlpath
  - xarray
  - zarr
  - pip:
      - carbonplan
